/**
 * Generate xast-style TypeScript interfaces for PreTeXt elements from the
 * official RELAX-NG schema. Run via:
 *
 *   npx tsx packages/ptxast/scripts/generate-types.ts
 *
 * Writes output to packages/ptxast/src/types/generated-interfaces.ts
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { unified } from 'unified';
import { fromXml } from 'xast-util-from-xml';
import { toXml } from 'xast-util-to-xml';
import type { Root } from 'xast';

// Import from the relax-ng-to-typescript TypeScript source (no built dist).
import {
  removePositionPlugin,
  doSimplificationPlugin,
  makeTypesForGrammar,
  renameRefsPlugin,
} from '../../../node_modules/relax-ng-to-typescript/src/index.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const workspaceRoot = path.resolve(__dirname, '../../..');

const rngPath = path.join(
  workspaceRoot,
  'extension',
  'assets',
  'schema',
  'pretext-dev.rng',
);

const outPath = path.join(
  __dirname,
  '../src/types/generated-interfaces.ts',
);

function unifiedXml() {
  return unified()
    .use(function () {
      // @ts-ignore
      this.Parser = fromXml;
    })
    .use(function () {
      // @ts-ignore
      this.Compiler = toXml;
    });
}

async function resolveIncludes(rngFilePath: string): Promise<string> {
  let content = await fs.readFile(rngFilePath, 'utf-8');
  const includeRegex = /<include\s+href=("|')(.*?)\1\s*\/>/g;
  let match: RegExpExecArray | null;
  while ((match = includeRegex.exec(content)) !== null) {
    const includePath = path.join(path.dirname(rngFilePath), match[2]);
    let included = await fs.readFile(includePath, 'utf-8');
    included = included.replace(/<\?xml.*?\?>/, '');
    included = included.replace(/<grammar[^>]*>/, '');
    included = included.replace(/<\/grammar>/, '');
    content = content.replace(match[0], included);
  }
  return content;
}

async function main() {
  console.log(`Reading RNG schema from: ${rngPath}`);
  const source = await resolveIncludes(rngPath);

  const processor = unifiedXml()
    .use(removePositionPlugin)
    .use(doSimplificationPlugin);

  const parsed = processor.parse(source);
  let ast = processor.runSync(parsed as any as Root);
  ast = unifiedXml().use(renameRefsPlugin).runSync(ast);

  const grammarTypes = makeTypesForGrammar((ast as Root).children[0]);

  const header = `// Generated by packages/ptxast/scripts/generate-types.ts from extension/assets/schema/pretext-dev.rng.
// Do not edit manually. Re-generate with: npx tsx packages/ptxast/scripts/generate-types.ts
// (or run: npm run refresh:schemas)
`;

  const output = header + grammarTypes.typescriptStr;
  await fs.writeFile(outPath, output, 'utf-8');
  console.log(`Wrote xast interfaces to: ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
