import { describe, expect, it } from "vitest";
import snapshot from "./converter-support.json";
import { ENVIRONMENTS } from "./environments";
import { MACROS } from "./macros";
import { PLUS_TYPES } from "./plus";

// The inverse of `converter-drift.spec.ts`.
//
// That spec asks "does everything we curated still convert?" — it catches
// support being *removed* upstream. This one asks "did we curate everything the
// converter supports?" — it catches support being *added*, which is how the
// tables went stale in the first place: the converter grew ten division macros
// and nothing noticed.
//
// The source of truth is `converter-support.json`, regenerated by
// `npm run refresh:latex-support`. Bump the converter, run that, and any new
// name shows up here by name.

const curatedEnvironments = new Set(
  ENVIRONMENTS.flatMap((e) => [e.name, ...e.aliases]),
);
const curatedMacros = new Set(MACROS.map((m) => m.name));
const macroByName = new Map(MACROS.map((m) => [m.name, m]));
const environmentByName = new Map(
  ENVIRONMENTS.flatMap((e) => [e.name, ...e.aliases].map((n) => [n, e])),
);

/**
 * Names the converter declares that the curated tables deliberately leave out.
 * Empty today; an entry here needs a reason, because the default answer to "the
 * converter supports this" is "then the editor should offer it".
 */
const INTENTIONALLY_OMITTED: Record<string, string> = {};

/**
 * Environments whose optional argument is not a title, so `titleArg` stays
 * false even though the converter's signature has an `o`. Each was checked by
 * converting a usage and looking at what came out.
 */
const OPTIONAL_ARG_IS_NOT_A_TITLE: Record<string, string> = {
  program:
    'the optional argument is the source language: [python] → language="python"',
  sidebyside:
    "the optional argument carries layout attributes (width, margins)",
  listing: "the converter currently drops the optional argument",
  list: "the converter currently mishandles the optional argument",
};

describe("every environment the converter supports is curated", () => {
  const names = Object.keys(snapshot.environments).filter(
    (name) => !(name in INTENTIONALLY_OMITTED),
  );

  it.each(names)("%s is in ENVIRONMENTS", (name) => {
    expect(curatedEnvironments).toContain(name);
  });

  it.each(names)("%s has a title argument iff the converter does", (name) => {
    const spec = environmentByName.get(name);
    if (!spec) return; // reported by the check above
    const converterHasOptional = snapshot.environments[name].includes("o");
    const expected =
      name in OPTIONAL_ARG_IS_NOT_A_TITLE ? false : converterHasOptional;
    expect(
      spec.titleArg,
      name in OPTIONAL_ARG_IS_NOT_A_TITLE
        ? `${name}: ${OPTIONAL_ARG_IS_NOT_A_TITLE[name]}`
        : `${name}: converter signature is "${snapshot.environments[name]}"`,
    ).toBe(expected);
  });
});

describe("every macro the converter supports is curated", () => {
  const names = Object.keys(snapshot.macros).filter(
    (name) => !(name in INTENTIONALLY_OMITTED),
  );

  it.each(names)("\\%s is in MACROS", (name) => {
    expect(curatedMacros).toContain(name);
  });

  it.each(names)("\\%s has the converter's signature", (name) => {
    const spec = macroByName.get(name);
    if (!spec) return; // reported by the check above
    expect(spec.signature, `\\${name}`).toBe(snapshot.macros[name]);
  });
});

// The converter handles ordinary LaTeX and PreTeXt inline markup through
// internal tables it does not export, so the refresh script finds those by
// probing every PreTeXt element name. `\alert` lived in that blind spot: fully
// supported by the converter, never curated, so the editor called it an unknown
// macro — and would have gone on doing so right after a quick fix inserted it.
describe("every probed macro is curated", () => {
  const names = snapshot.probedMacros.filter(
    (name) => !(name in INTENTIONALLY_OMITTED),
  );

  it.each(names)("\\%s is in MACROS", (name) => {
    expect(curatedMacros).toContain(name);
  });
});

describe("every probed environment is curated", () => {
  const names = snapshot.probedEnvironments.filter(
    (name) => !(name in INTENTIONALLY_OMITTED),
  );

  it.each(names)("%s is in ENVIRONMENTS", (name) => {
    expect(curatedEnvironments).toContain(name);
  });
});

describe("every plus include type the converter supports is curated", () => {
  it.each(snapshot.plusTypes)("%s is in PLUS_TYPES", (type) => {
    expect(PLUS_TYPES).toContain(type);
  });

  it("curates no type the converter does not know", () => {
    expect(
      [...PLUS_TYPES].filter((t) => !snapshot.plusTypes.includes(t)),
    ).toEqual([]);
  });
});

describe("waiver lists stay honest", () => {
  it("only waives names the converter actually declares", () => {
    const declared = new Set([
      ...Object.keys(snapshot.environments),
      ...Object.keys(snapshot.macros),
      ...snapshot.probedMacros,
      ...snapshot.probedEnvironments,
    ]);
    for (const name of Object.keys(INTENTIONALLY_OMITTED)) {
      expect(declared, `${name} is not declared by the converter`).toContain(
        name,
      );
    }
    for (const name of Object.keys(OPTIONAL_ARG_IS_NOT_A_TITLE)) {
      expect(
        snapshot.environments[name],
        `${name} is not a converter environment`,
      ).toBeDefined();
      expect(
        snapshot.environments[name].includes("o"),
        `${name} no longer has an optional argument — drop the waiver`,
      ).toBe(true);
    }
  });
});
