// Constants defining various tag categories in PreTeXt documents.
export const docStructure = [
  "abstract",
  "acknowledgement",
  "affiliation",
  "appendix",
  "article",
  "author",
  "backmatter",
  "biography",
  "book",
  "chapter",
  "colophon",
  "contributor",
  "contributors",
  "copyright",
  "credit",
  "dedication",
  "docinfo",
  "editor",
  "feedback",
  "frontmatter",
  "google",
  "html",
  "index",
  "macros",
  "mathbook",
  "preface",
  "pretext",
  "references",
  "search",
  "shortlicense",
  "solutions",
  "subsection",
  "titlepage",
  "website",
];
export const docSecs = [
  "assemblage",
  "chapter",
  "conclusion",
  "introduction",
  "objectives",
  "outcomes",
  "paragraphs",
  "part",
  "postlude",
  "prelude",
  "reading-questions",
  "sbsgroup",
  "section",
  "stack",
  "subsection",
  "subsubsection",
  "task",
  "technology",
  "worksheet",
];
export const docEnvs = [
  "activity",
  "algorithm",
  "answer",
  "axiom",
  "biblio",
  "blockquote",
  "case",
  "choice",
  "choices",
  "claim",
  "conjecture",
  "console",
  "corollary",
  "definition",
  "demonstration",
  "description",
  "example",
  "exercise",
  "exploration",
  "fact",
  "hint",
  "image",
  "images",
  "insight",
  "interactive",
  "investigation",
  "lemma",
  "list",
  "listing",
  "note",
  "openconjecture",
  "openproblem",
  "openquestion",
  "page",
  "poem",
  "principle",
  "problem",
  "program",
  "project",
  "proof",
  "proposition",
  "question",
  "remark",
  "shortdescription",
  "solution",
  "stanza",
  "statement",
  "subtask",
  "table",
  "tabular",
  "theorem",
  "video",
  "warning",
  "webwork",
];
export const lineEndTags = [
  "address",
  "attribution",
  "caption",
  "cline",
  "date",
  "department",
  "description",
  "edition",
  "entity",
  "holder",
  "idx",
  "institution",
  "journal",
  "line",
  "location",
  "minilicense",
  "mrow",
  "personname",
  "pg-macros",
  "pubtitle",
  "subtitle",
  "support",
  "title",
  "usage",
  "volume",
  "year",
  "xi:include",
  // Short scalar values — bibliography/metadata fields, publication settings, and
  // inline markup-documentation tags. Each belongs on one line with its tags;
  // otherwise appendBlock pushes the value onto a line of its own.
  "DOI",
  "ISBN",
  "ISSN",
  "archive",
  "attr",
  "de-number",
  "document-id",
  "dropping-particle",
  "email",
  "genre",
  "genus",
  "geometry",
  "initialism",
  "issue",
  "kbd",
  "literal",
  "macro-file",
  "mag",
  "non-dropping-particle",
  "number-of-pages",
  "page-first",
  "pages",
  "rename",
  "scaledeg",
  "series",
  "species",
  "static-ordering",
  "suffix",
  "tag",
  "tage",
  "watermark",
  "xhtml:button",
];
// empty tags that should be on their own line
const docEmpty = [
  "cell",
  "col",
  "notation-list",
  "brandlogo",
  "cross-references",
  "input",
  "video",
  "slate",
  "webwork",
];
const listLike = ["ol", "ul", "dl"];
const mathDisplay = ["me", "men", "md", "mdn"]; // me, men, and mdn are deprecated but still used in some documents
const nestableTags = [
  "ul",
  "ol",
  "li",
  "p",
  "task",
  "figure",
  "sidebyside",
  "notation",
  "row",
];
// note that c is special, because it is inline verbatim
export const verbatimTags = [
  "latex-image-preamble",
  "latex-image",
  "latex-preamble",
  "slate",
  "sage",
  "sageplot",
  "asymptote",
  "macros",
  "prefigure",
  "program",
  "preamble",
  "postamble",
  "input",
  "output",
  "prompt",
  "pre",
  "pg-code",
  "script",
  "tikzpicture",
  "tikz",
  "code",
  "c",
  "cd",
  // Code-carrying elements whose text is executed, rendered, or matched as-is.
  // Re-indenting them changes what they mean, so they must round-trip exactly.
  "strcmp", // literal/regex a fill-in answer is compared against
  "jscmp", // JavaScript comparison expression
  "mermaid", // Mermaid source; relative indentation is significant
  "stdin", // data piped to a <program>
  "asymptote-preamble",
  "setupScript", // JavaScript run before an <interactive> renders
  "postRenderScript", // JavaScript run after an <interactive> renders
  "source", // <interactive> source text
  "pf", // inline verbatim, like <c> — see isBlockChild in format.ts
];
export const newlineTags = [
  ...docStructure,
  ...docSecs,
  ...docEnvs,
  ...nestableTags,
  "xi:include",
];
export const blockTags = [
  ...docStructure,
  ...docSecs,
  ...docEnvs,
  ...nestableTags,
  ...mathDisplay,
  ...listLike,
];

// Elements with flowing text content that always expand to multiple lines.
export const parTags = ["p", "li", "fn"];

// Elements that prefer single-line when content fits within printWidth, but reflow
// like parTags when the line would be too long. Checked before lineEndTags in dispatch.
export const smartParTags = [
  "title",
  "shorttitle",
  "subtitle",
  "caption",
  "attribution",
  "personname",
  "location",
  "date",
  "edition",
  "entity",
  "support",
  "name",
  "given",
  "family",
  "usage",
  "volume",
  "number",
  "collection-title",
  "page",
  "year",
  "publisher",
  "publisher-place",
  "URL",
  "issued",
  "description",
  "shortdescription",
  "q",
  "premise",
  "response",
  "li",
  "cell",
  // Prose-like metadata: single line when it fits, reflowed when it does not.
  "blurb",
  "plaintitle",
];
