name: Publish VSCode Extension

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Dependencies
        run: npm install

      - name: Set up git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update schema
        run: |
          node ./scripts/getSchemas.js
          git add packages/vscode-extension/assets/schema
          git commit -m "chore: update schemas" || true

      - name: Build dependency packages
        run: npm run build:packages

      - name: Build Extension
        run: npm run build -w pretext-tools

      - name: Package
        run: |
          cd dist/vscode-extension
          npx vsce package --no-dependencies

      - name: Get Version
        id: version
        run: echo "VERSION=$(jq -r '.version' packages/vscode-extension/package.json)" >> $GITHUB_OUTPUT

      - name: Deploy to VS Marketplace
        run: |
          cd dist/vscode-extension
          npx vsce publish --no-dependencies -p ${{ secrets.VS_MARKETPLACE_TOKEN }}

      - name: Deploy to Open VSX
        run: |
          cd dist/vscode-extension
          npx ovsx publish --no-dependencies -p ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Update changelog
        run: |
          newline="\\n## [${{ steps.version.outputs.VERSION }}] - $(date +'%Y-%m-%d')"
          sed '/## \[UNRELEASED\]/a\'"$newline" CHANGELOG.md > CHANGELOG.md.tmp
          mv CHANGELOG.md.tmp CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "chore(vscode-extension): publish v${{ steps.version.outputs.VERSION }}" || true
          git push origin main

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ steps.version.outputs.VERSION }}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="v${{ steps.version.outputs.VERSION }}" \
            --notes="See the [changelog](CHANGELOG.md) for details."
