name: Pull Request Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: actions/setup-node@latest
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: |
          npx prettier -c $(git ls-files "*.ts")
          npx prettier -c $(git ls-files "snippets/*.json")
