name: Pull Request Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: |
          npx prettier -c $(git ls-files "packages/vscode-extension/*.ts")
          npx prettier -c $(git ls-files "snippets/*.json")
