name: test

on:
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: read version
        run: |
          value=$(jq '.version' package.json | tr -d '"')
          echo "VERSION=$value" >> $GITHUB_ENV
          echo "v${{ env.VERSION }}"
          newline="\\\n## [$value] - $(date +'%Y-%m-%d')"
          sed "/## [UNRELEASED]/a $newline" CHANGELOG.md > CHANGELOG.md.tmp

